# Wprowadzenie do badań internetowych {#intro}



<!-- You can label chapter and section titles using `{#label}` after them, e.g., we can reference Chapter \@ref(intro). If you do not manually label them, there will be automatic labels anyway, e.g., Chapter \@ref(methods). -->

<!-- Figures and tables with captions will be placed in `figure` and `table` environments, respectively. -->

<!-- ```{r nice-fig, fig.cap='Here is a nice figure!', out.width='80%', fig.asp=.75, fig.align='center'} -->
<!-- par(mar = c(4, 4, .1, .1)) -->
<!-- plot(pressure, type = 'b', pch = 19) -->
<!-- ``` -->

<!-- Reference a figure by its code chunk label with the `fig:` prefix, e.g., see Figure \@ref(fig:nice-fig). Similarly, you can reference tables generated from `knitr::kable()`, e.g., see Table \@ref(tab:nice-tab). -->

<!-- ```{r nice-tab, tidy=FALSE} -->
<!-- knitr::kable( -->
<!--   head(iris, 20), caption = 'Here is a nice table!', -->
<!--   booktabs = TRUE -->
<!-- ) -->
<!-- ``` -->

<!-- You can write citations, too. For example, we are using the **bookdown** package [@R-bookdown] in this sample book, which was built on top of R Markdown and **knitr** [@xie2015]. -->

## Źródła danych w statystyce

## Internet

Pokrycie internetu oraz jego wykorzystanie w Europie oraz Polsce

```{r pokrycie-internetu}
# internet <- search_eurostat(pattern  = 'internet')
# isoc_ci_ifp_iu  -- Individuals - internet use
# isoc_ci_ifp_fu -- Individuals - frequency of internet use
# isoc_ci_im_i -- Individuals - mobile internet access
dane <- get_eurostat(id = 'isoc_ci_ifp_iu', type = 'label')

dane %>% 
  filter(indic_is == 'Last internet use: in last 3 months' , 
         year(time) %in% 2010:2016,
         geo %in% c('Poland'),
         ind_type %in% c('All Individuals', 'Individuals, 16 to 24 years old',
           'Individuals, 25 to 34 years old',
           'Individuals, 35 to 44 years old',
           'Individuals, 45 to 54 years old',
           'Individuals, 55 to 74 years old'),
         unit == 'Percentage of individuals') %>%
  select(ind_type, time, values) %>%
  ggplot(data = .,
         aes(x = time,
             y = values,
             group = ind_type,
             colour = ind_type)) + 
  geom_line() +
  xlab('Okres badania') +
  ylab('Odsetek osób') +
  scale_colour_brewer(name = 'Przekrój',palette = 'Paired') +
  ggtitle('Odsetek korzystających z Internetu w ostatnich 3 miesiącach w Polsce')
```


## Definicje

### Definicje dotyczące badań 

Za @bethlehem2011handbook:

* Cross-sectional survey -- A survey that observes a sample from the target population at one point in time. The objective is to describe the state of the population at that moment in time.
* Longitudinal survey -- A survey that observes the same sample from the target population at several points in time. The objective is to describe the changes of the population over time.
* E-mail survey -- A form of data collection via the Internet in which respondents are sent a questionnaire that is part of the body text of an e-mail. The question- naire is completed by returning the e-mail after answering the questions in the text.
* Mail survey -- A form of data collection where paper questionnaire forms are sent to the respondents. After completion of the questionnaires, they are returned to the research organization.
* Web survey -- A form of data collection via the Internet in which respondents complete the questionnaires on the World Wide Web. The questionnaire is accessed by means of a link to a web page.
* Internet survey -- A general term for various forms of data collection via the Internet. Examples are a web survey and an e-mail survey. Included also are forms of data collection that use the Internet just to transport the questionnaire and the collected data.
* Self-selection survey - A survey for which the sample has been recruited by means of self-selection. It is left to the persons themselves to decide to participate in a survey.
* Self-selection panel: A web panel for which people select themselves in response to a banner, pop-up window, or advertisement in other media (radio, TV, and newspapers); Also Opt-in panel, Volunteer panel, Access panel.
* Web panel -- A survey in which the same individuals are interviewed via the web at different points in time.
* Mixed-mode survey -- A survey in which various modes of data collection are combined. Modes can be used concurrently (different groups are approached by different modes) or sequentially (nonrespondents of a mode are reapproached in a different mode).
* Reference survey -- A survey conducted with the objective to obtain unbiased estimates of the population distributions of auxiliary variables.

Za @callegaro2015web:

Przykłady paneli badawczych, w których dane zbierane są za pomocą interentu @callegaro2014online:

* General population panel -- are the most common. These panels tend to be very large and are recruited to include the diversity of the general population, sometimes including people in hard-to-reach subpopulations. A general population panel typically is used as a frame, from which samples are drawn based on the requirements of individual studies. 
* Specialty panel -- are designed to permit study of subpopulations de ned by demograph- ics and/or behavioral characteristics. 
* Proprietary panel -- are a subclass of specialty panels in which the members participate in research for a particular company. These panels are also called client panels, community panels, and, more recently, insight communities. They provide the opportunity for a company to establish a long-term relationship with a group of consumers – typically customers of products or services offered by the company – in a setting that allows for a mix of qualitative and quantitative research, of which surveying panels’ members is just one method of research.
* Election panels -- people eligible to vote are recruited, and then the panel is subsam- pled during the months before (and perhaps after) an election to study attitude formation and change. These panels resemble more traditional longitudinal panels, because each member is surveyed at each wave before and after the election 
* Internet audience ratings panels -- rely on passive data collection rather than surveys. Track a panelist’s browsing behavior via software installed on the panelist’s computer or by using other technologies, such as a router,6 to record the sites he or she visits, the amount of time spent on each site, and the actions taken on that site

## Literatura zalecana

Zachęcam do zapoznania z poniższymi raportami:

* [2016 -- Evaluating Survey Quality in Today's Complex Environment](http://www.aapor.org/AAPOR_Main/media/MainSiteFiles/AAPOR_Reassessing_Survey_Methods_Report_Final.pdf)
* [2015 -- Task Force Report on Big Data](http://www.aapor.org/getattachment/Education-Resources/Reports/BigDataTaskForceReport_FINAL_2_12_15_b.pdf.aspx)
* [2014 -- Current Knowledge and Considerations Regarding Survey Refusals](http://www.aapor.org/AAPOR_Main/media/MainSiteFiles/RefusalTF_FINAL090814.pdf)
* [2014 -- Social Media and Public Opinion Research](http://www.aapor.org/AAPOR_Main/media/MainSiteFiles/AAPOR_Social_Media_Report_FNL.pdf)
* [2014 -- Mobile Technologies for Conducting, Augmenting and Potentially Replacing Surveys](http://www.aapor.org/getattachment/Education-Resources/Reports/REVISED_Mobile_Technology_Report_Final_revised10June14.pdf.aspx)
* [2013 -- Non-Probability Sampling](http://www.aapor.org/AAPOR_Main/media/MainSiteFiles/NPS_TF_Report_Final_7_revised_FNL_6_22_13.pdf)
* [2010 -- Cell Phone Task Force Report](http://www.aapor.org/AAPOR_Main/media/MainSiteFiles/2010AAPORCellPhoneTFReport.pdf)
* [2010 -- Opt In Online Panel Task Force Report](http://poq.oxfordjournals.org/content/early/2010/10/19/poq.nfq048.full.pdf?ijkey=0w3WetMtGItMuXs&keytype=ref)


